RateMyWalk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rate_my_walk import views
#import redux regview and reverse helper
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

#Overriding a url in the redux package to redirect users after initial registration

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rate_my_walk:register_profile')

urlpatterns = [
    path('', views.index, name='index'),
    path('RateMyWalk/', include('rate_my_walk.urls')),
    path('admin/', admin.site.urls),
    #get redux package to use overriden class above
    path('accounts/register/',MyRegistrationView.as_view(),name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rate_my_walk/urls.py
from django.urls import path
from rate_my_walk import views

app_name = 'rate_my_walk'

urlpatterns = [
    #general urls
    path('', views.index, name='index'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('about/', views.about, name='about'),
    #walk urls
    path('walks/', views.walks, name='walks'),
    path("walks/<slug:walk_name_slug>/", views.showWalk, name='showWalk'),
    path("walks/<slug:walk_name_slug>/more-images/", views.moreImages, name='more_images'),
    path("walks/<slug:walk_name_slug>/rate-walk/", views.rateWalk, name='rateWalk'),
    path("upload/", views.uploadWalk, name='uploadWalk'),
    path("walks/edit/<slug:walk_name_slug>/", views.editWalk, name='edit_walk'),
    #profile urls
    path('register_profile/', views.register_profile,name='register_profile'),
    path('profile/<username>/',views.ProfileView.as_view(),name='profile'),
    path('walkers/',views.ListProfilesView.as_view(), name='list_walkers'),
    #like button url
    path('like_walk/', views.LikeWalk.as_view(), name='like_walk'),
]

rate_my_walk/forms.py
from django import forms
from rate_my_walk.models import WalkPage, Comment, Photo, Rating
from django.utils import timezone
#for userprofile
from rate_my_walk.models import UserProfile

class WalkPageForm(forms.ModelForm):
    
    name = forms.CharField(max_length=128,
                           help_text = "Please enter the name of your walk")
    desc = forms.CharField(max_length=2048,
                           help_text = "Please write the description of your walk here",
                           widget=forms.Textarea(attrs={'class': 'resizeForm'}))
    start = forms.CharField(max_length=128,
                            help_text = "Enter start location of your walk",
                            widget=forms.Textarea(attrs={'class': 'resizeForm'}))
    end = forms.CharField(max_length=128,
                          help_text = "Enter end location of your walk",
                          widget=forms.Textarea(attrs={'class': 'resizeForm'}))
    
    cover = forms.ImageField(help_text = "Upload picture of your walk", required=False)
    
    enjoyment = forms.IntegerField(initial = 0,
                                   help_text = "Rate enjoyment (0-10)",
                                   max_value = 10,
                                   min_value = 0)
    duration = forms.IntegerField(initial = 0,
                                  help_text = "Rate duration (0-10)",
                                  max_value = 10,
                                  min_value = 0)
    difficulty = forms.IntegerField(initial = 0, help_text = "Rate difficulty (0-10)",
                                    max_value = 10,
                                    min_value = 0)
    
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    date = forms.DateField(widget=forms.HiddenInput(), required=False)
    
    class Meta:
        model = WalkPage
        fields = ('name', 'desc', 'start', 'end', 'cover', 'enjoyment', 'duration', 'difficulty', )


class RatingForm(forms.ModelForm):
    duration = forms.IntegerField(help_text="Duration", initial = 0, max_value = 10, min_value = 0)
    difficulty = forms.IntegerField(help_text="Difficulty", initial = 0, max_value = 10, min_value = 0)
    enjoyment = forms.IntegerField(help_text="Enjoyment", initial = 0, max_value = 10, min_value = 0)

    #Class to give more info on the format
    class Meta:
        #associate between the model form and the rating
        model = Rating
        #hide foreign key
        exclude = ('walk', 'rater')

class PhotoForm(forms.ModelForm):
    	
	picture = forms.ImageField(help_text="If you also had a walk at this location you can upload a picture here")

	class Meta:
		model = Photo
		exclude = ('walk', 'owner', 'date')

class CommentForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text = "Please enter the title of your comment")
    comment = forms.CharField(max_length=256,
                              help_text = "Write your comment here",
                              widget=forms.Textarea(attrs={'class': 'resizeForm'}))
    date = forms.DateField(widget=forms.HiddenInput(), required=False)
    
    class Meta:
        model = Comment
        exclude = ('owner', 'walk', )

class DeleteWalkForm(forms.ModelForm):
    slug = forms.SlugField(widget=forms.HiddenInput())
    
    class Meta:
        model = WalkPage
        fields = ('slug', )

#Display a HTML form for the user profile details
class UserProfileForm(forms.ModelForm):
    website = forms.URLField(max_length=128, 
                             help_text="Please enter the URL of your social media, such as Facebook",
                             widget=forms.Textarea(attrs={'class': 'resizeForm'}))
    picture = forms.ImageField(help_text="Upload your profile picture here", required=True)

    class Meta:
        model = UserProfile
        fields=('website','picture',)

rate_my_walk/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from rate_my_walk.models import User, WalkPage, Comment, Photo, Rating, UserProfile
from rate_my_walk.forms import RatingForm, WalkPageForm, PhotoForm, CommentForm, DeleteWalkForm, UserProfileForm
from rate_my_walk.bing_search import run_query
from django.utils import timezone
from django.views.generic import View
from django.utils.decorators import method_decorator


def index(request):
    #here I use id as it's in the ER diagram, but for urls we would sue names so might be worth setting name up as a unique foreign key
    most_enjoyable = WalkPage.objects.order_by('-enjoyment')[:5]
    most_recent = WalkPage.objects.order_by('-date')[:5]
    context_dict = {'enjoyment': most_enjoyable,
                    'recent': most_recent}
    return render(request, 'rate_my_walk/index.html', context=context_dict)

def contact_us(request):
    context_dict = {}
    return render(request, 'rate_my_walk/contact_us.html', context=context_dict)

def about(request):
    context_dict = {}
    return render(request, 'rate_my_walk/about.html', context=context_dict)

def walks(request):
    allWalks = WalkPage.objects.order_by('-enjoyment')
    sort = 'enjoyment'

    if 'attribute' in request.POST:
        attribute = '-' + request.POST['attribute'].lower()
        allWalks = WalkPage.objects.order_by(attribute)
        sort = request.POST['attribute'].lower()
    context_dict = {'walk_list': allWalks,
                    'sort': sort,}
    
    return render(request, 'rate_my_walk/walks.html', context=context_dict)

def showWalk(request, walk_name_slug):
    context_dict = {}
    
    #check if walk exists based on slug
    try:
        walk = WalkPage.objects.get(slug = walk_name_slug)
        context_dict['walk'] = walk
    except WalkPage.DoesNotExist:
        context_dict['walk'] = None
        return redirect(reverse('rate_my_walk:index'))
    
    #get mean user ratings
    ratings = Rating.objects.filter(walk=walk)
    if ratings:
        counter = 0
        difficulty_sum = 0
        duration_sum = 0
        enjoyment_sum = 0
        
        for rating in ratings:
            difficulty_sum += rating.difficulty
            duration_sum += rating.duration
            enjoyment_sum += rating.enjoyment
            counter += 1
            
        difficulty_mean = round(difficulty_sum/counter,1)
        duration_mean = round(duration_sum/counter,1)
        enjoyment_mean = round(enjoyment_sum/counter,1)
        context_dict['duration'] = duration_mean
        context_dict['difficulty'] = difficulty_mean
        context_dict['enjoyment'] = enjoyment_mean

    #get all comments
    all_comments = Comment.objects.filter(walk=walk).order_by('-date')
    if all_comments:
        context_dict['comments'] = all_comments
    
    result_list = []
    query=""
    photo_form = PhotoForm()
    comment_form = CommentForm()
    context_dict['photo_form'] = photo_form
    context_dict['comment_form'] = comment_form
    
    delete_form = DeleteWalkForm()
    context_dict['delete_form'] = delete_form
    
    if request.method == 'POST':
        #search related post
        if 'query' in request.POST:
            query = request.POST['query'].strip()
            if query:
                result_list = run_query(query)
        
        #if post is about comments
        if 'comment' in request.POST and 'title' in request.POST:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                if walk:
                    newComment = comment_form.save(commit=False)
                    newComment.owner = request.user
                    newComment.walk = walk
                    newComment.date = timezone.now()
                    newComment.save()
                    return redirect(reverse('rate_my_walk:showWalk', kwargs={'walk_name_slug': walk_name_slug}))
            else:
                print(comment_form.errors)
        
        #extra image related post
        if 'picture' in request.FILES:
            photo_form = PhotoForm(request.POST, request.FILES)
            if photo_form.is_valid():
                if walk:
                    newPhoto = photo_form.save(commit=False)
                    newPhoto.walk = walk
                    newPhoto.owner = request.user
                    newPhoto.date = timezone.now()
                    newPhoto.save()
                    return redirect(reverse('rate_my_walk:more_images', kwargs = {'walk_name_slug': walk_name_slug}))
            else:
                print(photo_form.errors)
        
        #delete related post
        if 'slug' in request.POST:
            walk.delete()
            return redirect(reverse('rate_my_walk:index'))
            
        context_dict['result_list'] = result_list
        context_dict['last_query'] = query
        context_dict['photo_form'] = photo_form

    
    return render(request, 'rate_my_walk/walk.html', context=context_dict)

def moreImages(request, walk_name_slug):
    currentWalk = WalkPage.objects.get(slug=walk_name_slug)
    allImages = Photo.objects.filter(walk=currentWalk).order_by('-date')
    context_dict = {'images': allImages, 'walk':currentWalk}
    #returns all instances of the photo model. images.picture points to the actial pic
    return render(request, 'rate_my_walk/moreImages.html', context=context_dict)

@login_required()
def rateWalk(request, walk_name_slug):
    try:
        walk = WalkPage.objects.get(slug=walk_name_slug)
    except WalkPage.DoesNotExist:
        walk = None
    
    if walk is None:
        return redirect('/RateMyWalk/')
    
    form = RatingForm()
    
    if request.method == 'POST':
        form = RatingForm(request.POST)
        
        if form.is_valid():
            if walk:
                rating = form.save(commit = False)
                rating.walk = walk
                rating.rater = request.user
                rating.save()
                return redirect(reverse('rate_my_walk:showWalk', kwargs = {'walk_name_slug': walk_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'walk': walk}
    return render(request, 'rate_my_walk/rateWalk.html', context_dict)

@login_required()
def uploadWalk(request):
    form = WalkPageForm()
    
    if request.method == "POST":
        form = WalkPageForm(request.POST, request.FILES)
        
        if form.is_valid():
            new_walk = form.save(commit=False)
            new_walk.owner = request.user
            new_walk.save()
            return redirect(reverse('rate_my_walk:showWalk', kwargs = {'walk_name_slug': new_walk.slug}))
        else:
            print(form.errors)
    return render(request, 'rate_my_walk/uploadWalk.html', {'form': form})

@login_required()
def editWalk(request, walk_name_slug):
    #find the walk object to edit
    try:
        walk = WalkPage.objects.get(slug=walk_name_slug)
    except WalkPage.DoesNotExist:
        walk = None
    
    if walk is None:
        return redirect('/RateMyWalk/')
    
    #fill new form with current instance
    form = WalkPageForm(request.POST or None, instance=walk)
    
    #update all fields based on POST
    if form.is_valid():
        edit = form.save(commit=False)
        #update picture if needed
        if request.FILES:
            edit.cover = request.FILES['cover']
        #should we update date too?
        edit.save()
        return redirect(reverse('rate_my_walk:showWalk', kwargs = {'walk_name_slug': walk.slug}))
    
    context_dict = {'walk': walk,
                    'form': form}

    return render(request, 'rate_my_walk/editWalk.html', context = context_dict)     

@login_required()
def register_profile(request):

    form = UserProfileForm()
    
    if request.method=='POST':
        form = UserProfileForm(request.POST, request.FILES)
        
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user=request.user
            user_profile.save()
            
            return redirect(reverse('rate_my_walk:index'))
        else:
            # probably better to do soemthing else to make it more intuitive for the user
            print(form.errors)
    context_dict={'form': form}
    return render(request,'rate_my_walk/profile_registration.html', context_dict)
    


class ProfileView(View):

    #helper method
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            #will redirect to homepage, could make an error msg 
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': user_profile.website,
                               'picture': user_profile.picture})
        return (user, user_profile, form)

    #user has to be logged in for both get and post
    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rate_my_walk:index'))
        
        walks = WalkPage.objects.filter(owner=user)

        context_dict = {'user_profile': user_profile,
                        'selected_user': user, 'form': form, 'walks': walks}

        return render(request, 'rate_my_walk/profile.html',
                      context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rate_my_walk:index'))

templates/rate_my_walk/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rate My Walk - {% block title_block %}walk with us!{% endblock %}
    </title>
        
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/blog/blog.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/RMWcss.css' %}" />

    </head>
    
    <body>
        
        <div class="container">
            <header class="blog-header py-3">
                <div class="row flex-nowrap justify-content-between align-items-center">
                    <div class="col-4 pt-1">
                        <a class="link-secondary" href="{% url 'rate_my_walk:index' %}">
                        <img id=headerlogo src="{% static 'images/RMWlogo.png' %}" alt="RateMyWalk logo" />
                        </a>
                    </div>
                    <div class="col-4 text-center">
                        <a class="blog-header-logo text-dark">Rate My Walk</a>
                    </div>
                    <div class="col-4 d-flex justify-content-end align-items-center">
                        {% if user.is_authenticated %}
                            <p id="usernameHeaderDisplay">Signed in as {{ user.username }}</p>
                            <a class="btn btn-sm btn-outline-secondary" href="{% url 'auth_logout' %}" id="logout-button">Log Out</a>
                        {% else %}
                            <a class="btn btn-sm btn-outline-secondary" href="{% url 'auth_login' %}">Log In</a>
                            <a class="btn btn-sm btn-outline-secondary" href="{% url 'registration_register' %}">Sign Up</a>
                        {% endif %}
                    </div>
                </div>
            </header>
            
            <div class="nav-scroller py-1 mb-2 bg-dark">
                <nav class="nav d-flex justify-content-between">
                    <a class="p-2 link-secondary" href="{% url 'rate_my_walk:about' %}"><p class="navbarText">About</p></a>
                    <a class="p-2 link-secondary" href="{% url 'rate_my_walk:walks' %}" id="walks-hover"><p class="navbarText">Walks</p></a>
                  {% if user.is_authenticated %}
                    <a class="p-2 link-secondary" href="{% url 'rate_my_walk:uploadWalk' %}"><p class="navbarText">Upload a Walk</p></a>
                    <a class="p-2 link-secondary" href="{% url 'rate_my_walk:profile' username=user.username %}"><p class="navbarText">My Account</p></a>
                  {% else %}
                    <a class="p-2 link-secondary" href="{% url 'auth_login' %}"><p class="navbarText">Upload a Walk</p></a>
                    <a class="p-2 link-secondary" href="{% url 'auth_login' %}"><p class="navbarText">My Account</p></a>
                  {% endif %}
                 
                </nav>
            </div>
        
            <div class="row">

                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}{% endblock %}
                </main>

            </div>    

            <!-- FOOTER -->
            <footer class="bg-dark">
                <a href="{% url 'rate_my_walk:contact_us' %}"><p id="contact_usFooter">Contact Us</p></a>
                <p id="websiteMessage">Walk with us</p>
            </footer>
        
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/RateMyWalk-jquery.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/RateMyWalk-ajax.js' %}" crossorigin="anonymous"></script>
        <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js'></script>
        
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
        <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/feather-icons"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/blog/blog.js"></script>
    </body>
</html>

templates/rate_my_walk/walk.html
{% extends 'rate_my_walk/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ walk.name }}
{% endblock %}

{% block body_block %}

<div class = "jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">{{ walk.name }}</h1>
        </div>
</div>

<main class="container">
  <div class="row">
    <div class="col-md-6">

      <article class="blog-post">
        <h3>Description</h3>
        <p>{{ walk.desc }}</p>
        <br />
        <ul class="list-unstyled">
          <li><span data-feather="play"></span>Start walk on {{ walk.start }}</li>
          <li><span data-feather="stop-circle"></span>End walk on {{ walk.end }}</li>
        </ul>

      </article><!-- /.blog-post end of desc -->

      <article class="blog-post">
        <h3> Uploader(<a href="{%url 'rate_my_walk:profile' username=walk.owner %}">{{walk.owner}}'s</a>) Rating</h3>
        <div class="row">

            <div class="row-md-6">
            <ul class="list-unstyled">
                <li><span data-feather="star"></span>Difficulty: </li>
                <li><span data-feather="star"></span>Duration: </li>
                <li><span data-feather="star"></span>How Enjoyable: </li>
            </ul>
            </div>
            
            <div class="row-md-2">
            <ul class="list-unstyled">
                <li class="alignedRating">{{ walk.difficulty }}</li>
                <li class="alignedRating">{{ walk.duration }}</li>
                <li class="alignedRating">{{ walk.enjoyment }}</li>
            </ul>
            </div>
        </div>
        
      </article><!-- /.blog-post -->
        
      <article class="blog-post">
          
        <h3>This many people like {{ walk.name }}</h3>
          <div>
            <strong id="like_count">{{ walk.likes }}</strong> likes
            {% if user.is_authenticated %}
            <button id="like_btn"
            		data-walk_id="{{ walk.id }}"
            		class="btn bg-dark text-white btn-sm"
            		type="button">
                <span data-feather="thumbs-up"></span>
                Like Walk
            </button>
              <br />
            Like if you also enjoyed this walk!
            {% endif %}
          </div>
    </article>
        
        
    <article class="blog-post">
        <h3>User Ratings</h3>
        <div class="row">
			{% if difficulty %}
				<div class="row-md-6">
				<ul class="list-unstyled">
					<li><span data-feather="star"></span>Difficulty: </li>
					<li><span data-feather="star"></span>Duration: </li>
					<li><span data-feather="star"></span>How Enjoyable: </li>
				</ul>
				</div>
				
				<div class="row-md-2">
				<ul class="list-unstyled">
					<li class="alignedRating">{{ difficulty }}</li>
					<li class="alignedRating">{{ duration }}</li>
					<li class="alignedRating">{{ enjoyment }}</li>
				</ul>
				</div>
			{% else %}
				<span data-feather="star"></span>No one rated this walk yet.
			{% endif %}
        </div>
        
      </article><!-- /.blog-post -->

    </div>

    <div class="col-md-6">
        <div>
            <img id="walkImage" src="{{walk.cover.url}}" alt="{{ walk.name }}" />
        </div>
        <br />
        
        <div class="col-md-10">
        <div class="py-1 mb-2 bg-dark rounded">
            <nav class="nav d-flex justify-content-center">
                <a class="p-2 link-secondary" href="{% url 'rate_my_walk:more_images' walk.slug %}"><p class="navbarText">More Images</p></a>
            </nav>
        </div>    

        <div class="py-1 mb-2 bg-dark rounded">
            <nav class="nav d-flex justify-content-center">
            {% if user.is_authenticated %}
                <a class="p-2 link-secondary" href="{% url 'rate_my_walk:rateWalk' walk.slug %}"><p class="navbarText">Rate Walk Yourself</p></a>
            {% else %}
                 <a class="p-2 link-secondary" id="unauthenticated-user-rating">
                    <p class="navbarText">Rate Walk Yourself</p>
                </a>
            {% endif %}
            </nav>
        </div>
        		
        {% if user.is_authenticated and user == walk.owner %}
        <div class="py-1 mb-2 bg-dark rounded">
            <nav class="nav d-flex justify-content-center">
                <a class="p-2 link-secondary" href="{% url 'rate_my_walk:edit_walk' walk.slug %}"><p class="navbarText">Edit Walk</p></a>
			</nav>
		</div>
		
		<div class="py-1 mb-2 bg-dark rounded">
            <nav class="nav d-flex justify-content-center">
				<form id="delete" method="post" action="{% url 'rate_my_walk:showWalk' walk.slug %}", enctype="multipart/form-data">
					{% csrf_token %}
					{% for hidden in delete_form.hidden_fields %}
						{{ hidden }}
					{% endfor %}
					{% for field in delete_form.visible_fields %}
						{{ field.errors }}
						{{ field.help_text }}
						{{ field }}
					{% endfor %}
					<button class="btn" type="submit" name="submit" id="delete-walk">
						<p class="buttonText">Delete Walk</p>
					</button>
				</form>
			</nav>
		</div>
        {% endif %}
            
        </div>


		
    </div>

  </div><!-- /.row -->
    
    <div class="row">
    <div class="col-md-8">
        
        <h3>Comments on this walk</h3>
    <div id="commentScrollbox">
    <div class="card mb-6">
        <div class="card-body">
                {% if comments %}
                    <ul class="list-group">
                    {% for comment in comments %}
                        <li class="list-group-item">
                            <h5>{{comment.title}}</h5> <br />
                            <em>{{comment.comment}}</em> <br />
                            by <a href="{%url 'rate_my_walk:profile' username=comment.owner %}">{{comment.owner}}</a> <br />
					{{comment.date}}
                        </li>
                    {% endfor %}
      
                    </ul>
                {% else %}
                    <strong>No comments on this walk yet.</strong>
                {% endif %}
            </div>
        </div>
    </div>
    
    <br />
    <br />
    <br />
    <div><!-- search bar -->
        
    <h3>Use this to search for the walk using Bing!</h3>
	<form
		class="form-inline"
		id="user-form"
		method ="post"
		action="{% url 'rate_my_walk:showWalk' walk.slug %}"
	>
		{% csrf_token %}
		
		<div class="form-group">
			<input
				type="text"
				size="50"
				name="query"
				id="query"
				value="{{last_query}}">
		
		</div>
		
        <button class="py-1 mb-2 bg-dark rounded btn" type="submit" name="submit">
            <p class="buttonText">Search</p>
        </button>			
	</form>
  </div><!-- /search bar -->

  <div><!-- search results -->
	{% if result_list %}
		<h2>Results</h2>
		
		<div class="list-group">
		
			{% for result in result_list %}
				<div class="list-group-item">
					<h3 class="list-group-item-heading">
						<a href="{{ result.link }}">
							{{ result.title|safe|escape }}
						</a>
					</h3>
					<p class="list-group-item-text">
						{{ result.summary|safe|escape }}
					</p>
				</div>
			{% endfor %}
		</div>
			
	{% endif %}
	
  </div><!-- /search results -->

    </div>

    <div class="col-md-4">
        <div><!-- add new comment -->
            <h3>Add your own comment</h3>
            {% if user.is_authenticated %}
                <form id="comment_form" method="post" action="{% url 'rate_my_walk:showWalk' walk.slug %}", enctype="multipart/form-data">
                {% csrf_token %}
                {% for hidden in comment_form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in comment_form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}<br />
                    {{ field }}<br />
                {% endfor %}
                    <br />
                    <button class="py-1 mb-2 bg-dark rounded btn" type="submit" name="submit">
                        <p class="buttonText">Upload Comment</p>
                    </button>
                    <div class="p-5"></div>
                 </form>
            {% else %}
                <strong>You must be logged in to leave a comment.</strong>
            {% endif %}

        </div><!-- /add new comment -->
        
        <div><!-- add new photo for more images -->
        <div>
		<h3>Add your photo</h3>
            {% if user.is_authenticated %}
                <form id="photo_form" method="post" action="{% url 'rate_my_walk:showWalk' walk.slug %}", enctype="multipart/form-data">
                {% csrf_token %}
                {% for hidden in photo_form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in photo_form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}<br />
                    {{ field }}<br />
                {% endfor %}
                    <br />
                    <button class="py-1 mb-2 bg-dark rounded btn" type="submit" name="submit">
                        <p class="buttonText">Upload Picture</p>
                    </button>
                    <div class="p-5"></div>
            </form>
            {% else %}
                <strong>You must be logged in to upload an image.</strong>
            {% endif %}
            </div>
        </div><!-- /add new photo for more images -->
		
    </div>

  </div>

</main><!-- /.container -->

{% endblock %}